# Generated by Django 4.1.6 on 2023-02-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adolfadmin_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolfadmin',
            name='user_type',
            field=models.CharField(default='nan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributer',
            name='user_type',
            field=models.CharField(default='nan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_type',
            field=models.CharField(default='nan', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehical_type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('product_image', models.ImageField(default='default_product_image.png', upload_to='media/product_images')),
                ('item_desc', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=50)),
                ('price_bef_gst', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tax_rate', models.CharField(max_length=20)),
                ('price_bef_gst_pu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price_aft_gst_pu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_per_nos', models.PositiveIntegerField()),
                ('price_pernos_incl_gst', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mrp_incl_gst_pu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.adolfadmin')),
            ],
        ),
    ]
