# Generated by Django 4.1.6 on 2023-02-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_adolfadmin_user_type_distributer_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolfadmin',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='distributer',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='user_type',
        ),
    ]
