# Generated by Django 4.1.6 on 2023-02-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_adolfadmin_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
