# Generated by Django 4.1.6 on 2023-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_pricelist_added_by_alter_pricelist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
