# Generated by Django 4.1.6 on 2023-03-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_pricelist_quantity_alter_pricelist_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='distributer',
            name='adolfAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributers', to='dashboard.adolfadmin'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='product_image',
            field=models.ImageField(default='default_product_image.png', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='distributer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailers', to='dashboard.distributer'),
        ),
    ]
