# Generated by Django 4.1.6 on 2023-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_pricelist_color_alter_pricelist_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolfadmin',
            name='photo',
            field=models.FileField(default='defaults/default_profile_image.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='distributer',
            name='photo',
            field=models.FileField(default='defaults/default_profile_image.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='photo',
            field=models.FileField(default='defaults/default_profile_image.jpg', upload_to='profile_pics'),
        ),
    ]
