# Generated by Django 4.1.6 on 2023-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_adolfadmin_photo_alter_distributer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='product_image',
            field=models.ImageField(default='defaults/default_product_image.png', upload_to='product_images'),
        ),
    ]
