# Generated by Django 4.1.6 on 2023-03-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_pricelist_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='adolfadmin',
            name='company_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adolfadmin',
            name='photo',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='distributer',
            name='photo',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='product_image',
            field=models.ImageField(default='default_product_image.png', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='photo',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='OrderRet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('order_dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_orders', to='dashboard.orderdist')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.retailer')),
            ],
        ),
        migrations.AddField(
            model_name='orderdist',
            name='distributer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.distributer'),
        ),
        migrations.AddField(
            model_name='orderdist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pricelist'),
        ),
    ]
