# Generated by Django 4.1.6 on 2023-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_orderdist_alter_adolfadmin_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='adolfadmin',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adolfadmin',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='retailer',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='retailer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adolfadmin',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributer',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='distributer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='distributer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
