# Generated by Django 4.1.6 on 2023-03-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_retailer_shop_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributer',
            old_name='company_address',
            new_name='company_address_dist',
        ),
        migrations.RenameField(
            model_name='distributer',
            old_name='company_name',
            new_name='company_name_dist',
        ),
        migrations.RenameField(
            model_name='distributer',
            old_name='location',
            new_name='location_dist',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='company_address',
            new_name='company_address_ret',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='company_name',
            new_name='company_name_ret',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='location',
            new_name='location_ret',
        ),
        migrations.RemoveField(
            model_name='adolfadmin',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='adolfadmin',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='adolfadmin',
            name='location',
        ),
    ]
