# Generated by Django 4.1 on 2023-01-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
