# Generated by Django 4.1 on 2023-01-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adolf_staff',
            field=models.BooleanField(default=False, verbose_name='Adolf7 Admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_distributer',
            field=models.BooleanField(default=False, verbose_name='Distributer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_retailer',
            field=models.BooleanField(default=False, verbose_name='Retailer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
