# Generated by Django 4.1 on 2023-01-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_is_adolf_staff_user_is_distributer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
