# Generated by Django 4.1 on 2023-01-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_adolf_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_distributer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_retailer',
        ),
    ]
